-- `normativa` no tiene mas tabla propia que se pueda llenar sin publicar una cifra
-- normativa, y publicar una cifra inventada esta prohibido (regla 5): un conjunto de
-- parametros de ensayo con importes de mentira seria exactamente lo que el corpus
-- verificado existe para impedir. Lo que se siembra aqui es lo comun.
--
-- No es un hueco disimulado: el recuento por tabla se compara igual para las 19 tablas, y
-- las dos filas de `municipalidad` y las dos de `modulo_sistema` viajan de verdad.
